<?php
use Cartalyst\Sentinel\Users\Eloquent;
class CustomModel extends Illuminate\Database\Eloquent\Model
{
    protected $checkbox = [];

    public function update(array $attributes = [], array $options = [])
    {
        foreach ($this->checkbox as $item){
            if (!array_key_exists($item, $attributes)){
                $attributes[$item] = false;
            }
        }
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }
}